### ISSUE TITLE
Game Over Condition

### ISSUE THREAD

**Issue by tessapower** [tessapower/ggj-2024#11]
This issue is to discuss how we want to score the game, and how to decide when to end the game.

### Game Over Condition

In general, we have spoken about appealing to the king and his court, and I am of the opinion that we should introduce a "mood meter" which is affected by how well the player does at each mini-game. There are two ways we could go about this:

1. The mood meter increases when the player does well at the mini-game; this would be mini-game dependent, as some game mechanics allow for different scoring (e.g. average, good, perfect) and it would be easy to track if the player was doing well. The mood meter decreases when the player makes a mistake in the mini-game, e.g. missed a target, dropped a juggling ball. 
2. The mood meter increases if the player wins the mini-game and decreases if they lose the mini-game. This is assuming the mini-game has a way to indicate player has won/lost.

In both cases, I suggest the mood meter being too low and the player messing up one more time would cause the game to be over.

### Scoring

If the king is really entertained, then we could use this opportunity to introduce a score multiplier! Scoring would naturally be mini-game dependent, but they should have relatively similar "weightings" if there is a range of scores that the player can get depending on their performance.

@TFLGamer @ZedXC @Joooosef please feel free to comment with your own thoughts :)

**Comment by tessapower** [comment]
I just found out that Godot has a nice [Progress Bar](https://docs.godotengine.org/en/stable/classes/class_progressbar.html) that we could use for the Mood Meter!

**Comment by ZedXC** [comment]
so the king and audience would have an attention meter that would start full and slowly go down. for every successful minigame you boost the attention meter back up. Depending on how well you did in the minigame the meter would go up smaller or larger. If you fill the meter you get a score multiplier on the next game. The score would be how many games you complete during your run but if you had a score multiplier of 2X instead of getting one point for completing the minigame you'd get two
if you're able to fill the meter with the second minigame then it would go to 3X etc...

**Comment by tessapower** [comment]
@ZedXC Does the attention meter go down while the mini-game is running, so it decreases every x seconds?

**Comment by ZedXC** [comment]
yeah the meter is constantly going down as the game runs meaning that there's a bit more urgency to each game. Adds to the tension.

**Comment by tessapower** [comment]
@ZedXC Okay, sounds good! Would you like to implement this seeing as it's your vision? 😄

**Comment by ZedXC** [comment]
Okay so I had a bit of a think about it and I think I might be overcomplicating how simple this system actually reasonably needs to be. Im going to implement a bit of a simpler system see how that feels and then if its off I can see about the above system. For now I'm going to just do a you lose a minigame 3 times the game ends kind of thing.

**Comment by ZedXC** [comment]
Never mind did it the complicated way lmao
