### ISSUE TITLE
Create SFX for game

### ISSUE THREAD

**Issue by tessapower** [tessapower/ggj-2024#34]
A list of possible sound effects for the game:

- [x] Positive indicator for when the player does the right thing during a mini-game
- [x] Negative indicator for when the player makes a mistake during a mini-game
- [x] Negative reaction (e.g. booing?) for when the player fails a mini-game
- [x] Clicking (buttons)
- [x] Pause/Resume

**Comment by ZedXC** [comment]
- [x] Positive reactions: cheering, laughing. for when the player succeeds a mini-game
